
server:
  port: 8080
  tomcat:
      # 配置Tomcat编码,默认为UTF-8
      uri-encoding: UTF-8
      # 配置最大线程数
      max-threads: 1000



spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/springbootmybatis-test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root
        # 阿里巴巴druid数据库连接
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        # 配置获取连接等待超时的时间
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    #设置静态资源路径，多个以逗号分隔
    resources:
        static-locations: classpath:static/,file:static
    mvc:
        static-path-pattern: /**
    #devtools自动重启 热部署
    devtools:
        restart:
            #开启热部署
            enabled: true
            #修改如下的资源不会触发重启
            exclude: static/**,templates/**
    thymeleaf:
        #模板引擎编码
        encoding: UTF-8
        #关闭模板引擎的缓存
        cache: false
    redis:
        host: 127.0.0.1
        port: 6379
        pool:
            # 连接池中的最大空闲连接
            max-idle: 20
            # 连接池中的最小空闲连接
            min-idle: 1
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 20
            max-wait: 60000
        #默认是索引为0的数据库
        database: 0
        # 连接超时时间（毫秒）
        timeout: 600000

mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.ztes.pojo

#pagehelper 分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#通用Mapper配置
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true

#日志级别
logging:
    level: debug






